// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxnCFDFOhPacxw5AUayoZIDb8IJzv5eh4',
    appId: '1:593977252898:web:7962931c0bda8185e4fe7b',
    messagingSenderId: '593977252898',
    projectId: 'pantry-pal-2c997',
    authDomain: 'pantry-pal-2c997.firebaseapp.com',
    storageBucket: 'pantry-pal-2c997.firebasestorage.app',
    measurementId: 'G-2VKBTPPW5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTjwMj4mA1mXk3osZGXcfEMbql_H7eBOY',
    appId: '1:593977252898:android:acb9f9d9c4fbba39e4fe7b',
    messagingSenderId: '593977252898',
    projectId: 'pantry-pal-2c997',
    storageBucket: 'pantry-pal-2c997.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5EbefBtEQtVWpQorraA0H9jhszDgLVk0',
    appId: '1:593977252898:ios:8f9ba5848a65393be4fe7b',
    messagingSenderId: '593977252898',
    projectId: 'pantry-pal-2c997',
    storageBucket: 'pantry-pal-2c997.firebasestorage.app',
    iosClientId: '593977252898-69iu1j2p28s79onotpnbuln29mm1joqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.pantryPal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5EbefBtEQtVWpQorraA0H9jhszDgLVk0',
    appId: '1:593977252898:ios:8f9ba5848a65393be4fe7b',
    messagingSenderId: '593977252898',
    projectId: 'pantry-pal-2c997',
    storageBucket: 'pantry-pal-2c997.firebasestorage.app',
    iosClientId: '593977252898-69iu1j2p28s79onotpnbuln29mm1joqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.pantryPal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxnCFDFOhPacxw5AUayoZIDb8IJzv5eh4',
    appId: '1:593977252898:web:b50480e831459df0e4fe7b',
    messagingSenderId: '593977252898',
    projectId: 'pantry-pal-2c997',
    authDomain: 'pantry-pal-2c997.firebaseapp.com',
    storageBucket: 'pantry-pal-2c997.firebasestorage.app',
    measurementId: 'G-DGGK8HSJCC',
  );

}